### PR TITLE
Propagate labels and annotations from plans to jobs

### LINKED ISSUE #160: Support pod labels and annotations
**Is your feature request related to a problem? Please describe.**
I need to be able to apply pod annotations for the created jobs so that my log collection framework can route the logs to the indexer.

**Describe the solution you'd like**

Support for setting labels and annotations on upgrade.cattle.io/v1:Plan custom resource.

The full path to spec...labels is whatever the owners would want, but it should generate the Job with the .spec.template.metadata. with the labels and annotations provided.

Example implementation: 

```
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: job-name
...
spec:
  metadata
    labels:
      my-custom-label: one
    annotations:
      logging.io/index: my-index
  concurrency: 1
...
```

It would then generate job manifests similar to this:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-name-hostname
...
spec:
  template:
    metadata:
      name: job-name-hostname1
      labels:
        my-custom-label: one
      annotations:
        logging.io/index: my-index
...
 ```

### PR DESCRIPTION
**Pull request by sfackler**
The `cattle.io` filtering seems a bit sketchy - is there a better way to do that?

Closes #160

### CODE REVIEW

**Review by dweomer — CHANGES_REQUESTED** [review]
This looks alright to me but some tests that demonstrate it working as expected, for both inclusions and exclusions, are a must.

**Comment by sfackler** [comment]
Updated!

**Comment by sfackler** [comment]
I think the CI may be a bit broken? The s390x and manifest builds seem to never start running.

**Comment by brandond** [comment]
yes, we no longer have s390x runners; those steps and the s390x manifest need to be removed.

**Comment by sfackler** [comment]
Build's green!

**Review by dweomer — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Pull request merged**
