### PR TITLE
add columns to plan crd

### PR DESCRIPTION
**Pull request by Robbilie**
Solves #203

### CODE REVIEW

**Comment by Robbilie** [comment]
the generated crd should be the same this way

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
This will need to be rebased once https://github.com/rancher/system-upgrade-controller/pull/211 is merged so that CI can run.

**Comment by Robbilie** [comment]
@brandond rebased, cant really see anything though and not sure if drone has been triggered at all since its a PR based on a fork :)

**Comment by brandond** [comment]
Looks good: https://drone-pr.rancher.io/rancher/system-upgrade-controller/215

**Comment by Robbilie** [comment]
who can merge this? :)

**Comment by Robbilie** [comment]
Thanks :)
Is there a release scheduled?

**Comment by brandond** [comment]
Try with `v0.10.0-dev.3` once CI is done.

**Comment by Robbilie** [comment]
Is triggering the CI a manual process?

**Comment by brandond** [comment]
No, it should be done now. Release artifacts are all available.

**Comment by brandond** [comment]
should be sorted.

**Comment by Robbilie** [comment]
Seems to work fine :) I'll observe...

**Pull request merged**
